version: "3"

services:
  postgres:
    image: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    restart: always
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    command: -p $POSTGRES_PORT
    logging:
      driver: json-file
      options:
        max-size: 50m

volumes:
  postgres_volume:
